site_name: "Dax's Grimoire"

theme:
  name: material
  language: it
  palette:
    # ModalitÃ  scura (Slate + Ambra)
    - scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/paw 
        name: Passa alla modalitÃ  chiara
    # ModalitÃ  chiara
    - scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-sunny 
        name: Passa alla modalitÃ  scura

  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search:
      lang: it             # Ottimizza la ricerca per l'italiano
      separator: '[\s\-\.]+' # Aiuta a cercare parole unite da trattini
nav:
  - ğŸ  Home: index.md
  - ğŸ§  Strategie: 
      - âšœï¸ Jeanne d'Arc: strategie/jeanne.md
      - ğŸ¯ Ottomani: strategie/ottomani.md
      - ğŸŒ² Rus: strategie/rus.md
      - ğŸŒ™ Ayyubidi: strategie/ayyubidi.md
      - ğŸ‡¯ğŸ‡µ Giapponesi: strategie/giapponesi.md
      - ğŸ˜ Delhi: strategie/delhi.md
      - ğŸ‘¹ Sengoku: strategie/sengoku.md
      - ğŸ›ï¸ Bizantini: strategie/bizantini.md
      - ğŸ›ï¸ Macedoni: strategie/macedoni.md
  - âš”ï¸ Enciclopedia CiviltÃ :
      - ğŸ•Œ Abbasidi: civilta/abbasidi.md
      - ğŸŒ™ Ayyubidi: civilta/ayyubidi.md
      - ğŸ›ï¸ Bizantini: civilta/bizantini.md
      - ğŸ‡¨ğŸ‡³ Cinesi: civilta/cinesi.md
      - ğŸ˜ Delhi: civilta/delhi.md
      - ğŸ‡«ğŸ‡· Francesi: civilta/francesi.md
      - ğŸ‡¯ğŸ‡µ Giapponesi: civilta/giapponesi.md
      - ğŸ´ó §ó ¢ó ¥ó ®ó §ó ¿ Inglesi: civilta/inglesi.md
      - âšœï¸ Jeanne d'Arc: civilta/jeanne.md
      - ğŸ›ï¸ Macedoni: civilta/macedoni.md
      - ğŸ‡²ğŸ‡± Maliani: civilta/maliani.md
      - ğŸ‡²ğŸ‡³ Mongoli: civilta/mongoli.md
      - â›º Orda d'Oro: civilta/orda.md
      - ğŸ² Order of the Dragon: civilta/dragon.md
      - ğŸ¯ Ottomani: civilta/ottomani.md
      - ğŸŒ² Rus: civilta/rus.md
      - ğŸ‘‘ Sacro Romano Imp.: civilta/hre.md
      - ğŸ‘¹ Sengoku: civilta/sengoku.md
      - ğŸ‘³ Tughlaq: civilta/tughlaq.md
      - ğŸ® Zhu Xi's Legacy: civilta/zhuxi.md