site_name: "Dax's Grimoire"

theme:
  name: material
  language: it
  features:
    - navigation.tabs        # Menu in alto orizzontale (piÃ¹ pulito)
    - navigation.sections    # Raggruppa le sezioni
    - toc.integrate          # Indice integrato a sinistra
    - navigation.top         # Bottone "Torna su"
    - search.suggest         # Suggerimenti ricerca
    - content.code.copy      # Bottone copia per il codice

  palette:
    # ModalitÃ  Scura (Default)
    - scheme: slate
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Passa alla modalitÃ  chiara

    # ModalitÃ  Chiara (Opzionale)
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Passa alla modalitÃ  scura

  font:
    text: Roboto    # Font molto leggibile
    code: Roboto Mono

# Aggiungi questo per caricare il CSS personalizzato (Passo 2)
extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search:
      lang: it             # Ottimizza la ricerca per l'italiano
      separator: '[\s\-\.]+' # Aiuta a cercare parole unite da trattini
nav:
  - Home: index.md
  - Strategia:
      - âšœï¸ Jeanne d'Arc:
          - 'Tower Rush (Dark Age)': strategia/jeanne/tower_rush.md
          - 'Wheelbarrow Rush': strategia/jeanne/wheelbarrow_rush.md
  - âš”ï¸ Enciclopedia CiviltÃ :
      - ğŸ•Œ Abbasidi: civilta/abbasidi.md
      - ğŸŒ™ Ayyubidi: civilta/ayyubidi.md
      - ğŸ›ï¸ Bizantini: civilta/bizantini.md
      - ğŸ‡¨ğŸ‡³ Cinesi: civilta/cinesi.md
      - ğŸ˜ Delhi: civilta/delhi.md
      - ğŸ‡«ğŸ‡· Francesi: civilta/francesi.md
      - ğŸ‡¯ğŸ‡µ Giapponesi: civilta/giapponesi.md
      - ğŸ´ó §ó ¢ó ¥ó ®ó §ó ¿ Inglesi: civilta/inglesi.md
      - âšœï¸ Jeanne d'Arc: civilta/jeanne.md
      - ğŸ›ï¸ Macedoni: civilta/macedoni.md
      - ğŸ‡²ğŸ‡± Maliani: civilta/maliani.md
      - ğŸ‡²ğŸ‡³ Mongoli: civilta/mongoli.md
      - â›º Orda d'Oro: civilta/orda.md
      - ğŸ² Order of the Dragon: civilta/dragon.md
      - ğŸ¯ Ottomani: civilta/ottomani.md
      - ğŸŒ² Rus: civilta/rus.md
      - ğŸ‘‘ Sacro Romano Imp.: civilta/hre.md
      - ğŸ‘¹ Sengoku: civilta/sengoku.md
      - ğŸ‘³ Tughlaq: civilta/tughlaq.md
      - ğŸ® Zhu Xi's Legacy: civilta/zhuxi.md