site_name: "Dax's Grimoire"
site_url: https://wuaandax-boop.github.io/grimoire/

theme:
  name: material
  language: it
  palette:
    - scheme: slate
      primary: black
      accent: gold
  features:
    - navigation.top
    - search.suggest

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/stats.js

nav:
  - Home: index.md
  - Strategia:
    - Panoramica: strategia/index.md
    - Jeanne d'Arc:
        - 'Indice': strategia/jeanne/index.md
        - 'Tower Rush': strategia/jeanne/tower_rush.md
        - 'Wheelbarrow Rush': strategia/jeanne/wheelbarrow_rush.md
    - Rus:
        - 'Indice': strategia/rus/index.md
        - '2 Hunting Cabin': strategia/rus/2hc.md
        - '3 Hunting Cabin': strategia/rus/3hc.md
    - Ayyubids:
        - 'Vortix': strategia/ayyubids/vortix.md
    - Ottoman:
        - 'ASAP School': strategia/ottoman/asap-school.md
        - 'Standard': strategia/ottoman/standard.md
    - Macedon:
        - 'Standard': strategia/macedon/standard.md
        - 'IDK': strategia/macedon/idk.md
    - Byzantines:
        - 'Standard': strategia/byz/standard.md
        - 'IDK': strategia/byz/idk.md
    - Japan:
        - 'Fast Castle': strategia/japan/fc.md
        - 'Standard': strategia/japan/standard.md
    - Sengoku:
        - 'Standard': strategia/sengoku/standard.md