site_name: "Dax's Grimoire"
site_url: https://wuaandax-boop.github.io/grimoire/ # IMPORTANTE: Sostituisci col tuo vero URL GitHub

theme:
  name: material
  language: it
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - content.code.copy

  palette:
    - scheme: slate
      primary: black # Cambiato in black per far risaltare l'oro
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Passa alla modalitÃ  chiara
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Passa alla modalitÃ  scura

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/stats.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list # Necessario per gestire meglio le immagini e classi CSS

nav:
  - Home: index.md
  - Strategia:
      - ğŸ° Panoramica: strategia/index.md
      - ğŸ›¡ï¸ Jeanne d'Arc:
          - 'Tower Rush (Dark Age)': strategia/jeanne/tower_rush.md
          - 'Wheelbarrow Rush': strategia/jeanne/wheelbarrow_rush.md
      - ğŸ» Rus:
          - '2 Hunting Cabin': strategia/rus/2hc.md
          - '3 Hunting Cabin': strategia/rus/3hc.md
      - ğŸª Ayyubids:
          - 'Vortix': strategia/ayyubids/vortix.md
      - ğŸ’£ Ottoman:
          - 'ASAP School': strategia/ottoman/asap-school.md
          - 'Standard': strategia/ottoman/standard.md
      - ğŸ›ï¸ Macedon:
          - 'Standard': strategia/macedon/standard.md
          - 'IDK': strategia/macedon/idk.md
      - ğŸ‡ Byzantines:
          - 'Standard': strategia/byz/standard.md
          - 'IDK': strategia/byz/idk.md
      - â›©ï¸ Japan:
          - 'Fast Castle': strategia/japan/fc.md
          - 'Standard': strategia/japan/standard.md
      - ğŸ¯ Sengoku:
          - 'Standard': strategia/sengoku/standard.md